Update comment_on_issues.yml

diff --git a/.github/workflows/comment_on_issues.yml b/.github/workflows/comment_on_issues.yml
--- a/.github/workflows/comment_on_issues.yml
+++ b/.github/workflows/comment_on_issues.yml
@@ -176,12 +176,24 @@ jobs:
           emoji: eyes
 
       - name: Install Ubuntu Dependencies
-        if: env.iscustom == 'true' && success()
         uses: awalsh128/cache-apt-pkgs-action@latest
         with:
-          packages: ca-certificates patchelf e2fsprogs aria2 p7zip-full attr unzip xz-utils qemu-utils python3-venv erofs-utils linux-modules-extra-azure
+          packages: ca-certificates patchelf e2fsprogs aria2 p7zip-full attr unzip xz-utils qemu-utils python3-venv erofs-utils
           version: 1.0
           
+      - name: Setup Python3 Virtual Enviroment
+        working-directory: scripts
+        run: |
+          PYTHON_VENV_DIR="$(dirname "$PWD")/python3-env"
+          python3 -m venv "$PYTHON_VENV_DIR" || abort "Failed to create python3 virtual env"
+          # shellcheck disable=SC1091
+          source "$PYTHON_VENV_DIR/bin/activate" || abort "Failed to activate python3 virtual env"
+          python3 -c "import pkg_resources; pkg_resources.require(open('requirements.txt',mode='r'))" &>/dev/null || {
+              echo "Installing Python3 dependencies"
+              python3 -m pip install --upgrade -r requirements.txt || abort "Failed to install python3 dependencies"
+          }
+          deactivate
+
       - name: Update Package
         if: env.iscustom == 'true' && success()
         working-directory: scripts
