Use Python3 virtual environments (#17)

diff --git a/.github/workflows/comment_on_issues.yml b/.github/workflows/comment_on_issues.yml
--- a/.github/workflows/comment_on_issues.yml
+++ b/.github/workflows/comment_on_issues.yml
@@ -13,6 +13,7 @@ on:
 
 jobs:
   build:
+    if: ${{github.repository == 'YT-Advanced/WSA-Script'}}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -47,7 +48,6 @@ jobs:
           sudo apt-get update -y
           sudo apt-get install -y lzip
           python3 -m pip install --upgrade pip setuptools
-          python3 -m pip install --upgrade -r scripts/requirements.txt
 
       - name: Get Issues Info
         if: github.event_name == 'issues'
@@ -179,8 +179,23 @@ jobs:
         if: env.iscustom == 'true' && success()
         uses: awalsh128/cache-apt-pkgs-action@latest
         with:
-          packages: ca-certificates patchelf e2fsprogs aria2 p7zip-full attr unzip xz-utils qemu-utils
+          packages: ca-certificates patchelf e2fsprogs aria2 p7zip-full attr unzip xz-utils qemu-utils python3-venv
           version: 1.0
+          
+      - name: Update Package
+        if: env.iscustom == 'true' && success()
+        working-directory: scripts
+        run: |
+          PYTHON_VENV_DIR="$(dirname "$PWD")/python3-env"
+          echo "Creating Python3 Virtual Enviroment"
+          python3 -m venv "$PYTHON_VENV_DIR" || abort "Failed to create python3 virtual env"
+          # shellcheck disable=SC1091
+          source "$PYTHON_VENV_DIR/bin/activate" || abort "Failed to activate python3 virtual env"
+          python3 -c "import pkg_resources; pkg_resources.require(open('requirements.txt',mode='r'))" &>/dev/null || {
+              echo "Installing Python3 dependencies"
+              python3 -m pip install --upgrade -r requirements.txt || abort "Failed to install python3 dependencies"
+          }
+          deactivate 
 
       - name: Run Build
         id: wsa
diff --git a/.github/workflows/custom_build.yml b/.github/workflows/custom_build.yml
--- a/.github/workflows/custom_build.yml
+++ b/.github/workflows/custom_build.yml
@@ -42,7 +42,7 @@ on:
         type: choice
         description: Compression format.
         required: true
-        options: [".zip",".7z",".xz"]
+        options: [".zip",".7z",".tar.xz"]
         default: ".7z"
       remove_amazon:
         description: "Remove Amazon AppStore from the system"
@@ -93,22 +93,32 @@ jobs:
           cache: 'pip'
           cache-dependency-path: scripts/
 
-      - name: Update Package 👷
-        run: |
-          sudo apt-get update -y
-          sudo apt-get install -y lzip
-          python3 -m pip install --upgrade -r scripts/requirements.txt
-    
       - name: Install Ubuntu Dependencies 🧑‍🏭
         uses: awalsh128/cache-apt-pkgs-action@latest
         with:
-          packages: ca-certificates patchelf e2fsprogs aria2 p7zip-full attr unzip xz-utils qemu-utils
+          packages: ca-certificates patchelf e2fsprogs aria2 p7zip-full attr unzip xz-utils qemu-utils python3-venv
           version: 1.0
+          
+      - name: Update Package 👷
+        working-directory: scripts
+        run: |
+          sudo apt-get update -y
+          sudo apt-get install -y lzip
+          PYTHON_VENV_DIR="$(dirname "$PWD")/python3-env"
+          echo "Creating Python3 Virtual Enviroment"
+          python3 -m venv "$PYTHON_VENV_DIR" || abort "Failed to create python3 virtual env"
+          # shellcheck disable=SC1091
+          source "$PYTHON_VENV_DIR/bin/activate" || abort "Failed to activate python3 virtual env"
+          python3 -c "import pkg_resources; pkg_resources.require(open('requirements.txt',mode='r'))" &>/dev/null || {
+              echo "Installing Python3 dependencies"
+              python3 -m pip install --upgrade -r requirements.txt || abort "Failed to install python3 dependencies"
+          }
+          deactivate
 
       - name: Build WSA 🏗️
         id: wsa
         run: |
-          declare -A opts=( ["RELEASE_TYPE,Retail"]="retail" ["RELEASE_TYPE,Release Preview"]="RP" ["RELEASE_TYPE,Insider Slow"]="WIS" ["RELEASE_TYPE,Insider Fast"]="WIF" ["ROOT_SOL,Magisk Stable"]="stable" ["ROOT_SOL,Magisk Beta"]="beta" ["ROOT_SOL,Magisk Canary"]="canary" ["ROOT_SOL,Magisk Debug"]="debug" ["ROOT_SOL,Magisk Delta (HuskyDG)"]="delta" ["ROOT_SOL,Magisk Alpha (vvb2060)"]="alpha" ["ROOT_SOL,KernelSU"]="kernelsu" ["ROOT_SOL,Non-root"]="none" ["GAPPS_BRAND,OpenGApps v11.0"]="OpenGApps" ["GAPPS_BRAND,MindTheGapps v13.0"]="MindTheGapps" ["GAPPS_BRAND,No GApps"]="none" ["GAPPS_VAR,Pico"]="pico" ["GAPPS_VAR,Nano"]="nano" ["GAPPS_VAR,Micro"]="micro" ["GAPPS_VAR,Mini"]="mini" ["GAPPS_VAR,Full"]="full" ["GAPPS_VAR,Stock"]="stock" ["GAPPS_VAR,Super"]="super" ["GAPPS_VAR,TVStock"]="tvstock" ["GAPPS_VAR,TVMini"]="tvmini" ["REMOVE_AMAZON,true"]="--remove-amazon" ["COMPRESSION,.zip"]="zip" ["COMPRESSION,.7z"]="7z" ["COMPRESSION,.xz"]="xz" )
+          declare -A opts=( ["RELEASE_TYPE,Retail"]="retail" ["RELEASE_TYPE,Release Preview"]="RP" ["RELEASE_TYPE,Insider Slow"]="WIS" ["RELEASE_TYPE,Insider Fast"]="WIF" ["ROOT_SOL,Magisk Stable"]="stable" ["ROOT_SOL,Magisk Beta"]="beta" ["ROOT_SOL,Magisk Canary"]="canary" ["ROOT_SOL,Magisk Debug"]="debug" ["ROOT_SOL,Magisk Delta (HuskyDG)"]="delta" ["ROOT_SOL,Magisk Alpha (vvb2060)"]="alpha" ["ROOT_SOL,KernelSU"]="kernelsu" ["ROOT_SOL,Non-root"]="none" ["GAPPS_BRAND,OpenGApps v11.0"]="OpenGApps" ["GAPPS_BRAND,MindTheGapps v13.0"]="MindTheGapps" ["GAPPS_BRAND,No GApps"]="none" ["GAPPS_VAR,Pico"]="pico" ["GAPPS_VAR,Nano"]="nano" ["GAPPS_VAR,Micro"]="micro" ["GAPPS_VAR,Mini"]="mini" ["GAPPS_VAR,Full"]="full" ["GAPPS_VAR,Stock"]="stock" ["GAPPS_VAR,Super"]="super" ["GAPPS_VAR,TVStock"]="tvstock" ["GAPPS_VAR,TVMini"]="tvmini" ["REMOVE_AMAZON,true"]="--remove-amazon" ["COMPRESSION,.zip"]="zip" ["COMPRESSION,.7z"]="7z" ["COMPRESSION,.tar.xz"]="xz" )
           if [[ "${{ inputs.root_sol }}" == *Magisk* ]]; then
               MAGISK_VER="${opts[ROOT_SOL,${{ inputs.root_sol }}]}"
               ROOT_SOL="magisk"
@@ -116,8 +126,9 @@ jobs:
               ROOT_SOL="${opts[ROOT_SOL,${{ inputs.root_sol }}]}"
               MAGISK_VER="${opts[ROOT_SOL,Magisk Stable]}"
           fi
-
-          if [[ ! "$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.user_code')" == "" ]]; then
+          if [[ -z "$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.user_code')" ]]; then
+              echo -e "\n:: Using default User code ::\n"
+          else
               mkdir -p download
               echo -e "user_code=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.user_code')" > download/.ms_account
               echo -e "\n:: Using MS Insiders User code ::\n"
