Update custom_build.yml

diff --git a/.github/workflows/custom_build.yml b/.github/workflows/custom_build.yml
--- a/.github/workflows/custom_build.yml
+++ b/.github/workflows/custom_build.yml
@@ -79,6 +79,29 @@ jobs:
     steps:
       - name: Checkout ♻️
         uses: actions/checkout@v3
+         
+      - name: Eenviroments variables setup
+        run: |
+          declare -A opts=( \
+              ["RELEASE_TYPE,Retail"]="retail" ["RELEASE_TYPE,Release Preview"]="RP" ["RELEASE_TYPE,Insider Slow"]="WIS" ["RELEASE_TYPE,Insider Fast"]="WIF" \
+              ["ROOT_SOL,Magisk Stable"]="stable" ["ROOT_SOL,Magisk Beta"]="beta" ["ROOT_SOL,Magisk Canary"]="canary" ["ROOT_SOL,Magisk Debug"]="debug" \
+              ["ROOT_SOL,Magisk Delta (HuskyDG)"]="delta" ["ROOT_SOL,Magisk Alpha (vvb2060)"]="alpha" ["ROOT_SOL,KernelSU"]="kernelsu" ["ROOT_SOL,Non-root"]="none" \
+              ["GAPPS_BRAND,MindTheGapps v13.0"]="MindTheGapps" ["GAPPS_BRAND,No GApps"]="none" ["REMOVE_AMAZON,true"]="--remove-amazon" \
+              ["COMPRESSION,.zip"]="zip" ["COMPRESSION,.7z"]="7z" ["COMPRESSION,.tar.xz"]="xz" )
+          
+          if [[ "${{ inputs.root_sol }}" == *Magisk* ]]; then
+              MAGISK_VER="${opts[ROOT_SOL,${{ inputs.root_sol }}]}"
+              ROOT_SOL="magisk"
+          else
+              ROOT_SOL="${opts[ROOT_SOL,${{ inputs.root_sol }}]}"
+              MAGISK_VER="${opts[ROOT_SOL,Magisk Stable]}"
+          fi
+          
+          if [[ "$ROOT_SOL" == "none" ]] && [[ "${opts[GAPPS_BRAND,${{ inputs.gapps_brand }}]}" == "none" ]] && [[ "${opts[REMOVE_AMAZON,${{ inputs.remove_amazon }}]}" != "--remove-amazon" ]]; then
+              echo -e "\nBUILD FAILED\n"
+              echo -e "The option you choiced does not require you to run this build.\nThere is no need to change the configuration, just install directly from the Microsoft Store.\nhttps://apps.microsoft.com/store/detail/9P3395VX91NR\n\n"
+              exit 1
+          fi
 
       - name: Get WSA Insider Preview build 🏭
         if: inputs.release_type == 'Insider Private'
@@ -139,21 +162,7 @@ jobs:
 
       - name: Build WSA 🏗️
         id: wsa
-        run: |
-          declare -A opts=( ["RELEASE_TYPE,Retail"]="retail" ["RELEASE_TYPE,Release Preview"]="RP" ["RELEASE_TYPE,Insider Slow"]="WIS" ["RELEASE_TYPE,Insider Fast"]="WIF" ["ROOT_SOL,Magisk Stable"]="stable" ["ROOT_SOL,Magisk Beta"]="beta" ["ROOT_SOL,Magisk Canary"]="canary" ["ROOT_SOL,Magisk Debug"]="debug" ["ROOT_SOL,Magisk Delta (HuskyDG)"]="delta" ["ROOT_SOL,Magisk Alpha (vvb2060)"]="alpha" ["ROOT_SOL,KernelSU"]="kernelsu" ["ROOT_SOL,Non-root"]="none" ["GAPPS_BRAND,MindTheGapps v13.0"]="MindTheGapps" ["GAPPS_BRAND,No GApps"]="none" ["REMOVE_AMAZON,true"]="--remove-amazon" ["COMPRESSION,.zip"]="zip" ["COMPRESSION,.7z"]="7z" ["COMPRESSION,.tar.xz"]="xz" )
-          if [[ "${{ inputs.root_sol }}" == *Magisk* ]]; then
-              MAGISK_VER="${opts[ROOT_SOL,${{ inputs.root_sol }}]}"
-              ROOT_SOL="magisk"
-          else
-              ROOT_SOL="${opts[ROOT_SOL,${{ inputs.root_sol }}]}"
-              MAGISK_VER="${opts[ROOT_SOL,Magisk Stable]}"
-          fi
-          
-          if [[ "$ROOT_SOL" == "none" ]] && [[ "${opts[GAPPS_BRAND,${{ inputs.gapps_brand }}]}" == "none" ]] && [[ "${opts[REMOVE_AMAZON,${{ inputs.remove_amazon }}]}" != "--remove-amazon" ]]; then
-              echo -e "\nBUILD FAILED\n\nNot all options need to go through this build.\nThere is no need to change the configuration, just install directly from the Microsoft Store."
-              exit 1
-          fi
-          
+        run: |          
           mkdir -p download
           echo -e "user_code=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.user_code')" > download/.ms_account
 
