Update custom_build.yml

diff --git a/.github/workflows/custom_build.yml b/.github/workflows/custom_build.yml
--- a/.github/workflows/custom_build.yml
+++ b/.github/workflows/custom_build.yml
@@ -100,6 +100,7 @@ jobs:
           version: 1.0
           
       - name: Update Package 👷
+        working-directory: scripts
         run: |
           sudo apt-get update -y
           sudo apt-get install -y lzip
@@ -107,9 +108,9 @@ jobs:
           python3 -m venv "python3-env" || abort "Failed to create python3 virtual env"
           # shellcheck disable=SC1091
           source "python3-env/bin/activate || abort "Failed to activate python3 virtual env"
-          python3 -c "import pkg_resources; pkg_resources.require(open('./scripts/requirements.txt',mode='r'))" &>/dev/null || {
+          python3 -c "import pkg_resources; pkg_resources.require(open('requirements.txt',mode='r'))" &>/dev/null || {
               echo "Installing Python3 dependencies"
-              python3 -m pip install --upgrade -r scripts/requirements.txt || abort "Failed to install python3 dependencies"
+              python3 -m pip install --upgrade -r requirements.txt || abort "Failed to install python3 dependencies"
           }
           deactivate
           
