Update custom_build.yml

diff --git a/.github/workflows/custom_build.yml b/.github/workflows/custom_build.yml
--- a/.github/workflows/custom_build.yml
+++ b/.github/workflows/custom_build.yml
@@ -104,16 +104,17 @@ jobs:
         run: |
           sudo apt-get update -y
           sudo apt-get install -y lzip
+          PYTHON_VENV_DIR="$(dirname "$PWD")/python3-env"
           echo "Creating Python3 Virtual Enviroment"
-          python3 -m venv "python3-env" || abort "Failed to create python3 virtual env"
+          python3 -m venv "$PYTHON_VENV_DIR" || abort "Failed to create python3 virtual env"
           # shellcheck disable=SC1091
-          source "python3-env/bin/activate" || abort "Failed to activate python3 virtual env"
+          source "$PYTHON_VENV_DIR/bin/activate" || abort "Failed to activate python3 virtual env"
           python3 -c "import pkg_resources; pkg_resources.require(open('requirements.txt',mode='r'))" &>/dev/null || {
               echo "Installing Python3 dependencies"
               python3 -m pip install --upgrade -r requirements.txt || abort "Failed to install python3 dependencies"
           }
           deactivate
-          
+
       - name: Build WSA 🏗️
         id: wsa
         run: |
@@ -130,7 +131,6 @@ jobs:
           else
               mkdir -p download
               echo -e "user_code=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.user_code')" > download/.ms_account
-              echo "user_code=$(cat $GITHUB_EVENT_PATH | jq -r '.inputs.user_code')"
               echo -e "\n:: Using MS Insiders User code ::\n"
           fi
           
