Update custom_build.yml

diff --git a/.github/workflows/custom_build.yml b/.github/workflows/custom_build.yml
--- a/.github/workflows/custom_build.yml
+++ b/.github/workflows/custom_build.yml
@@ -93,17 +93,29 @@ jobs:
           cache: 'pip'
           cache-dependency-path: scripts/
 
+      - name: Install Ubuntu Dependencies 🧑‍🏭
+        uses: awalsh128/cache-apt-pkgs-action@latest
+        with:
+          packages: ca-certificates patchelf e2fsprogs aria2 p7zip-full attr unzip xz-utils qemu-utils python3-venv
+          version: 1.0
+          
       - name: Update Package 👷
         run: |
           sudo apt-get update -y
           sudo apt-get install -y lzip
-          python3 -m pip install --upgrade -r scripts/requirements.txt
-    
-      - name: Install Ubuntu Dependencies 🧑‍🏭
-        uses: awalsh128/cache-apt-pkgs-action@latest
-        with:
-          packages: ca-certificates patchelf e2fsprogs aria2 p7zip-full attr unzip xz-utils qemu-utils
-          version: 1.0
+          
+          PYTHON_VENV_DIR="$(dirname "$PWD")/python3-env"
+          [ -f "$PYTHON_VENV_DIR/bin/activate" ] || {
+          echo "Creating Python3 Virtual Enviroment"
+          python3 -m venv "$PYTHON_VENV_DIR" || abort "Failed to create python3 virtual env"
+          }
+          # shellcheck disable=SC1091
+          source "$PYTHON_VENV_DIR"/bin/activate || abort "Failed to activate python3 virtual env"
+          python3 -c "import pkg_resources; pkg_resources.require(open('requirements.txt',mode='r'))" &>/dev/null || {
+              echo "Installing Python3 dependencies"
+              python3 -m pip install -r requirements.txt || abort "Failed to install python3 dependencies"
+          }
+          deactivate
 
       - name: Build WSA 🏗️
         id: wsa
